services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gnars-web-dev
    ports:
      - "0.0.0.0:3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
