import { Metadata } from "next";
import { notFound, redirect } from "next/navigation";
import { getProfile, setApiKey } from "@zoralabs/coins-sdk";
import { isAddress, type Address } from "viem";
import { MemberDetail } from "@/components/members/MemberDetail";
import { BASE_URL } from "@/lib/config";
import { MEMBERS_MINIAPP_EMBED_CONFIG } from "@/lib/miniapp-config";
import { resolveAddressFromENS } from "@/lib/ens";
import { serverPublicClient } from "@/lib/rpc";
import { fetchMemberOverview } from "@/services/members";

export const dynamic = "force-dynamic";

/**
 * Minimal ABI for detecting + resolving the admin of a thirdweb EIP-4337
 * smart account. Standard account implementations expose `owner()` —
 * multi-sig variants expose `getAllSigners()` but we only handle the
 * common single-owner case. If the call reverts we gracefully fall
 * through to rendering the contract address as-is.
 */
const ACCOUNT_OWNER_ABI = [
  {
    name: "owner",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address", name: "" }],
  },
] as const;

/**
 * Detects whether the given address is a deployed contract on Base and,
 * if so, attempts to read `owner()` to find the admin EOA. Returns the
 * resolved EOA address when successful, `null` when the address is an
 * EOA to begin with, and `undefined` when the contract doesn't expose
 * an owner (unknown account implementation).
 */
async function resolveSmartAccountOwner(
  address: Address,
): Promise<Address | null | undefined> {
  try {
    const code = await serverPublicClient.getCode({ address });
    if (!code || code === "0x") return null; // EOA
    const owner = (await serverPublicClient.readContract({
      address,
      abi: ACCOUNT_OWNER_ABI,
      functionName: "owner",
    })) as Address;
    return owner;
  } catch {
    return undefined;
  }
}

interface MemberPageProps {
  params: Promise<{ address: string }>;
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}

// Helper to fetch member metadata for OG tags
async function getMemberMetadata(address: string) {
  try {
    // Fetch Zora profile data
    if (process.env.NEXT_PUBLIC_ZORA_API_KEY) {
      setApiKey(process.env.NEXT_PUBLIC_ZORA_API_KEY);
    }

    const [zoraProfile, memberOverview] = await Promise.all([
      getProfile({ identifier: address }).catch(() => null),
      fetchMemberOverview(address).catch(() => null),
    ]);

    const profile = zoraProfile?.data?.profile;
    const displayName =
      profile?.displayName || profile?.handle || `${address.slice(0, 6)}...${address.slice(-4)}`;
    const avatar = profile?.avatar?.medium || profile?.avatar?.small;
    const tokenCount = memberOverview?.tokenCount || 0;

    // Safely access creatorCoin properties
    const creatorCoin = profile?.creatorCoin as
      | {
          address?: string;
          name?: string;
          symbol?: string;
          marketCap?: string;
          marketCapDelta24h?: string;
          mediaContent?: {
            previewImage?: {
              small?: string;
              medium?: string;
              blurhash?: string;
            };
          };
        }
      | undefined;

    // Use avatar or creator coin image if available
    const imageUrl =
      avatar ||
      creatorCoin?.mediaContent?.previewImage?.medium ||
      creatorCoin?.mediaContent?.previewImage?.small ||
      `${BASE_URL}/logo-banner.jpg`;

    return {
      displayName,
      imageUrl,
      tokenCount,
      hasCreatorCoin: !!creatorCoin,
      creatorCoinName: creatorCoin?.name,
    };
  } catch (error) {
    console.error("Error fetching member metadata:", error);
    return null;
  }
}

export async function generateMetadata({ params }: MemberPageProps): Promise<Metadata> {
  const { address } = await params;

  // Check if it's a valid address
  if (!isAddress(address)) {
    return {
      title: "Member Not Found | Gnars DAO",
      description: "The member profile you're looking for doesn't exist.",
    };
  }

  const metadata = await getMemberMetadata(address);

  if (!metadata) {
    return {
      title: `${address.slice(0, 6)}...${address.slice(-4)} | Gnars DAO`,
      description: "View this member's profile on Gnars DAO.",
    };
  }

  const { displayName, tokenCount, hasCreatorCoin, creatorCoinName } = metadata;

  // Build description based on available data
  const descriptionParts = [];
  if (tokenCount > 0) {
    descriptionParts.push(`${tokenCount} Gnar${tokenCount !== 1 ? "s" : ""}`);
  }
  if (hasCreatorCoin && creatorCoinName) {
    descriptionParts.push(`Creator of ${creatorCoinName}`);
  }
  const description =
    descriptionParts.length > 0
      ? `${displayName}: ${descriptionParts.join(" • ")}`
      : `View ${displayName}'s profile on Gnars DAO`;

  const memberUrl = `${BASE_URL}/members/${address}`;

  // Dynamic OG image will be auto-generated by opengraph-image.tsx
  const ogImageUrl = `${memberUrl}/opengraph-image`;

  // Build dynamic miniapp embed with member-specific data
  const miniappEmbed = {
    ...MEMBERS_MINIAPP_EMBED_CONFIG,
    imageUrl: ogImageUrl,
    button: {
      ...MEMBERS_MINIAPP_EMBED_CONFIG.button,
      title: `View ${displayName}`,
      action: {
        ...MEMBERS_MINIAPP_EMBED_CONFIG.button.action,
        url: memberUrl,
      },
    },
  };

  return {
    title: `${displayName} | Gnars DAO`,
    description,
    openGraph: {
      title: displayName,
      description,
      images: [ogImageUrl],
      type: "profile",
      url: memberUrl,
    },
    twitter: {
      card: "summary_large_image",
      title: displayName,
      description,
      images: [ogImageUrl],
    },
    other: {
      "fc:miniapp": JSON.stringify(miniappEmbed),
    },
  };
}

export default async function MemberPage({ params, searchParams }: MemberPageProps) {
  const [{ address }, sp] = await Promise.all([params, searchParams]);
  if (!isAddress(address)) {
    // Treat as ENS name and try to resolve
    if (address && address.includes(".")) {
      const resolved = await resolveAddressFromENS(address);
      if (resolved) {
        const qs = new URLSearchParams();
        if (sp) {
          for (const [key, value] of Object.entries(sp)) {
            if (typeof value === "string") {
              qs.set(key, value);
            } else if (Array.isArray(value)) {
              for (const v of value) qs.append(key, v);
            }
          }
        }
        const suffix = qs.toString();
        redirect(suffix ? `/members/${resolved}?${suffix}` : `/members/${resolved}`);
      }
      notFound();
    }
    notFound();
  }

  // If the URL address is a deployed smart account, redirect to its admin
  // EOA's profile. The joint-fetch logic at the EOA page aggregates data
  // from both sides, so landing on the EOA is canonical.
  const owner = await resolveSmartAccountOwner(address);
  if (owner && owner.toLowerCase() !== address.toLowerCase()) {
    const qs = new URLSearchParams();
    for (const [key, value] of Object.entries(sp ?? {})) {
      if (typeof value === "string") {
        qs.set(key, value);
      } else if (Array.isArray(value)) {
        for (const v of value) qs.append(key, v);
      }
    }
    const suffix = qs.toString();
    redirect(suffix ? `/members/${owner}?${suffix}` : `/members/${owner}`);
  }

  return (
    <div className="py-8">
      <MemberDetail address={address} />
    </div>
  );
}
