/**
 * VideoThumbnailSelector Component
 *
 * Allows users to scrub through a video and select which frame to use as thumbnail
 */

"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Check, Pause, Play, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { VideoPlayer, VideoPlayerRef } from "@/components/ui/video-player";

interface VideoThumbnailSelectorProps {
  videoFile: File;
  onThumbnailSelected: (thumbnailFile: File) => void;
  onCancel: () => void;
}

export function VideoThumbnailSelector({
  videoFile,
  onThumbnailSelected,
  onCancel,
}: VideoThumbnailSelectorProps) {
  const videoPlayerRef = useRef<VideoPlayerRef>(null);
  const pendingSeekRef = useRef<Promise<void> | null>(null);

  const [isPlaying, setIsPlaying] = useState(false);
  const [duration, setDuration] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [thumbnailPreview, setThumbnailPreview] = useState<string | null>(null);
  const [videoError, setVideoError] = useState<string | null>(null);
  const [isVideoReady, setIsVideoReady] = useState(false);

  const handleVideoError = useCallback((error: string) => {
    setVideoError(error);
    setIsVideoReady(false);
  }, []);

  const handleVideoLoaded = useCallback(() => {
    setVideoError(null);
    setIsVideoReady(true);
  }, []);

  const handleDurationChange = useCallback((newDuration: number) => {
    setDuration(newDuration);
    // Set initial time - preview will be generated by useEffect when ready
    const initialTime = Math.min(1, newDuration * 0.1);
    videoPlayerRef.current?.seekTo(initialTime);
    setCurrentTime(initialTime);
  }, []);

  const handleTimeUpdate = useCallback((newTime: number) => {
    setCurrentTime(newTime);
  }, []);

  const generatePreview = useCallback(
    async (time?: number) => {
      try {
        const player = videoPlayerRef.current;
        if (!player || !isVideoReady) {
          return;
        }

        // Wait for any pending seek to complete first
        if (pendingSeekRef.current) {
          await pendingSeekRef.current;
        }

        if (time !== undefined) {
          player.seekTo(time);
          // Wait for the seeked event instead of arbitrary timeout
          const seekPromise = player.waitForSeek();
          pendingSeekRef.current = seekPromise;
          await seekPromise;
          pendingSeekRef.current = null;
        }

        const thumbnailFile = await player.captureFrame();
        const previewUrl = URL.createObjectURL(thumbnailFile);

        // Clean up previous URL before setting new one
        setThumbnailPreview((prevUrl) => {
          if (prevUrl) {
            URL.revokeObjectURL(prevUrl);
          }
          return previewUrl;
        });
      } catch (error) {
        // Log errors in development for debugging
        if (process.env.NODE_ENV !== 'production') {
          console.error('Failed to generate thumbnail preview:', error);
        }
        // User can still use auto-thumbnail if preview generation fails
      }
    },
    [isVideoReady],
  );

  // Generate initial preview when video becomes ready
  useEffect(() => {
    if (isVideoReady && duration > 0 && !thumbnailPreview) {
      const initialTime = Math.min(1, duration * 0.1);
      generatePreview(initialTime);
    }
  }, [isVideoReady, duration, thumbnailPreview, generatePreview]);

  // Cleanup blob URL on unmount
  useEffect(() => {
    return () => {
      if (thumbnailPreview) {
        URL.revokeObjectURL(thumbnailPreview);
      }
    };
  }, [thumbnailPreview]);

  const togglePlayPause = useCallback(() => {
    const player = videoPlayerRef.current;
    if (!player) return;

    if (isPlaying) {
      player.pause();
      setIsPlaying(false);
    } else {
      player.play();
      setIsPlaying(true);
    }
  }, [isPlaying]);

  const handleSliderChange = useCallback(
    (values: number[]) => {
      const time = values[0];
      videoPlayerRef.current?.seekTo(time);
      setCurrentTime(time);
      if (isVideoReady) {
        generatePreview(time);
      }
    },
    [generatePreview, isVideoReady],
  );

  const resetToDefault = useCallback(() => {
    const defaultTime = Math.min(1, duration * 0.1);
    videoPlayerRef.current?.seekTo(defaultTime);
    setCurrentTime(defaultTime);
    if (isVideoReady) {
      generatePreview(defaultTime);
    }
  }, [duration, generatePreview, isVideoReady]);

  const handleSelectThumbnail = useCallback(async () => {
    setIsGenerating(true);
    try {
      const player = videoPlayerRef.current;
      if (!player) {
        throw new Error("Video player not available");
      }

      const thumbnailFile = await player.captureFrame();
      onThumbnailSelected(thumbnailFile);
    } catch {
      // Handle error silently or show user-friendly message
    } finally {
      setIsGenerating(false);
    }
  }, [onThumbnailSelected]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle className="text-lg">Select Video Thumbnail</CardTitle>
        <p className="text-sm text-muted-foreground">
          Choose which moment in your video to use as the thumbnail image
        </p>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Video Player */}
        <div className="relative">
          {videoError ? (
            <div className="w-full aspect-video rounded-lg border bg-red-50 flex flex-col items-center justify-center">
              <div className="text-center p-6">
                <p className="text-red-600 font-medium">Video Playback Error</p>
                <div className="text-red-500 text-sm mt-2 mb-4 whitespace-pre-line">
                  {videoError}
                </div>
                <div className="space-y-3">
                  <p className="text-gray-600 text-sm font-medium">
                    No worries! We can extract a thumbnail automatically.
                  </p>
                  <Button
                    onClick={async () => {
                      setIsGenerating(true);
                      try {
                        const player = videoPlayerRef.current;
                        if (player) {
                          const thumbnail = await player.captureFrame();
                          onThumbnailSelected(thumbnail);
                        }
                      } catch {
                        // Auto thumbnail generation failed silently
                      } finally {
                        setIsGenerating(false);
                      }
                    }}
                    disabled={isGenerating}
                    size="default"
                    className="min-w-40 bg-blue-600 hover:bg-blue-700"
                  >
                    {isGenerating ? "Generating..." : "Generate Auto Thumbnail"}
                  </Button>
                </div>
              </div>
            </div>
          ) : (
            <>
              <VideoPlayer
                ref={videoPlayerRef}
                file={videoFile}
                className="w-full aspect-video object-contain rounded-lg border bg-black"
                onError={handleVideoError}
                onLoadedData={handleVideoLoaded}
                onTimeUpdate={handleTimeUpdate}
                onDurationChange={handleDurationChange}
              />

              {/* Play/Pause Overlay */}
              <Button
                variant="secondary"
                size="icon"
                className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70"
                onClick={togglePlayPause}
              >
                {isPlaying ? (
                  <Pause className="h-6 w-6 text-white" />
                ) : (
                  <Play className="h-6 w-6 text-white" />
                )}
              </Button>

              {/* Time Display */}
              <div className="absolute bottom-2 right-2 bg-black/50 text-white text-xs px-2 py-1 rounded">
                {formatTime(currentTime)} / {formatTime(duration)}
              </div>
            </>
          )}
        </div>

        {/* Scrub Controls */}
        {!videoError && duration > 0 && (
          <div className="space-y-3">
            <Label>Select Thumbnail Moment</Label>
            <Slider
              value={[currentTime]}
              onValueChange={handleSliderChange}
              max={duration}
              min={0}
              step={0.1}
              className="w-full"
            />

            <div className="flex justify-between items-center">
              <Button variant="outline" size="sm" onClick={resetToDefault}>
                <RotateCcw className="h-4 w-4 mr-2" />
                Reset to Default
              </Button>

              <div className="text-sm text-muted-foreground">
                Current: {formatTime(currentTime)}
              </div>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex justify-end gap-2 pt-4">
          <Button variant="outline" onClick={onCancel}>
            Cancel
          </Button>
          <Button
            onClick={handleSelectThumbnail}
            disabled={isGenerating || !!videoError}
            className="min-w-24"
          >
            {isGenerating ? (
              "Generating..."
            ) : (
              <>
                <Check className="h-4 w-4 mr-2" />
                Use This Thumbnail
              </>
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
